### ISSUE TITLE
Rapid execution

### ISSUE THREAD

**Issue by karel-brinda** [cobilab/geco3#4]
Hello,

would it be possible to add an example to readme with a rapid mode of execution? I'm seeking st eq to `gzip --fast`.

I can do quick end-to-end tests with small files, but it's not always sufficient for testing the scripts / files.

Thanks !

**Comment by pratas** [comment]
Hi, 

It is there in "Example usage" -- Reference free:
./GeCo3 -l 1 -lr 0.06 -hs 8 BuEb

This compressed the sequence BuEb using level 1 (lowest) and with a "fast" neural network.

Cheers
